### ISSUE TITLE
gw_build_geocoder error

### ISSUE THREAD

**Issue by Logowilliams** [slu-openGIS/gateway#15]
Hi Chris! @jesnstevens and I are using the `gateway` package to geocode crime points in St. Louis and am running into an issue with the `gw_build_geocoder` function. I was originally trying this: 

> `geocoder <- gw_build_geocoder(class = "sf")` 

but getting the error:

> `Error in gw_build_geocoder(class = "sf") : unused argument (class = "sf")`

I then tried:

> `geocoder <- gw_build_geocoder(sf)`

and ran into the following error:

> `Error in "parcel" %in% return : object 'sf' not found`

I was hoping you had some guiding thoughts that could help me through these errors, thanks!

**Comment by chris-prener** [comment]
Hi @Logowilliams - this is getting reshuffled as we get ready to launch the package. If you use `gw_build_geocoder()` on its own, it now returns a single list object with all three geocoders in it. Once you geocode, you can project the data. We're not going to support the `sf` option moving forward due to performance issues.
